
all: True
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase }}_mock.go"
structname: "{{.InterfaceName}}Mock"
recursive: True
pkgname: "{{.SrcPackageName}}_mock"
template: testify
packages:
  github.com/nice-pea/npchat/internal/controller/http2/middleware: 
  github.com/nice-pea/npchat/internal/controller/http2/register_handler: 