all: True
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase }}_mock.go"
structname: "{{.InterfaceName | firstUpper}}"
recursive: True
pkgname: "mock{{.SrcPackageName | camelcase | firstUpper }}"
template: testify
packages:
  github.com/nice-pea/npchat/internal/controller/http2/middleware: 
  github.com/nice-pea/npchat/internal/controller/http2/register_handler: 
  github.com/nice-pea/npchat/internal/usecases/events: 