### Check server availability
GET http://localhost:8080/ping

### Create new chat
POST http://localhost:8080/chats
Content-Type: application/json
Accept: application/json
X-Request-ID: {{$uuid}}
Authorization: Bearer {{$uuid}}

{
  "name": "Test Chat",
  "description": "This is a test chat"
}

### Get user chats
GET http://localhost:8080/chats
Content-Type: application/json
Accept: application/json
X-Request-ID: {{$uuid}}
Authorization: Bearer {{$uuid}}


### Init google registration
GET http://localhost:8080/oauth/google/registration
Content-Type: application/json
Accept: application/json