### Variables
@baseUrl = http://localhost:8080

### Check server availability
GET {{baseUrl}}/ping

### Create new chat
POST {{baseUrl}}/chats
Content-Type: application/json
Accept: application/json
X-Request-ID: {{$uuid}}
Authorization: Bearer {{$uuid}}

{
  "name": "Test Chat",
  "description": "This is a test chat"
}

### Get user chats
GET {{baseUrl}}/chats
Content-Type: application/json
Accept: application/json
X-Request-ID: {{$uuid}}
Authorization: Bearer {{$uuid}}

### Vars
@oauthProvider = github

### Init oauth registration
GET {{baseUrl}}/oauth/{{oauthProvider}}/registration
Content-Type: application/json
Accept: application/json

### Complete oauth registration
@oauthState = variable value
@oauthCode = variable value
GET {{baseUrl}}/oauth/{{oauthProvider}}/callback?code={{oauthCode}}&state={{oauthState}}
Content-Type: application/json
Accept: application/json