
###
@host = http://localhost:7511
@saitoken = f1d727b2-212e-47cf-a7a2-40ff581bc816

### Healthcheck
GET {{host}}/health
#Accept-Language: ru
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
#Accept-Language: en-us,en;q=0.5

### Chats list
GET {{host}}/chats?ids=1&user_ids=1

### Messages list
GET {{host}}/messages?around_id=5&limit=5

### Message create
POST {{host}}/messages/create
Content-Type: application/json

{
  "chat_id": 1,
  "text": "text!",
  "author_id": 1,
  "reply_to_id": 0
}

### Members list
GET {{host}}/members?is_pinned=&

### Member create
POST {{host}}/members/create
Content-Type: application/json

{
  "user_id": 1,
  "chat_id": 1
}

### Permissions list
GET {{host}}/permissions

### Create new session
GET {{host}}/login?key=kk

### User update
POST {{host}}/chats/create
Content-Type: application/json

{
  "name": "some2",
  "creator_id": 1
}

### User and session information
GET {{host}}/authn?token={{saitoken}}

### Users list
GET {{host}}/users

### User update
POST {{host}}/users/update
Content-Type: application/json

{
  "id": 1,
  "username": "qwerty"
}