package http2

import "github.com/nice-pea/npchat/internal/controller/http2/register_handler"

// RequiredUsecases определяет интерфейс для доступа к сценариям использования бизнес-логики
type RequiredUsecases interface {
	registerHandler.UsecasesForAcceptInvitation
	registerHandler.UsecasesForLoginByPassword
	registerHandler.UsecasesForRegistrationByPassword
	registerHandler.UsecasesForCancelInvitation
	registerHandler.UsecasesForChatInvitations
	registerHandler.UsecasesForChatMembers
	registerHandler.UsecasesForCreateChat
	registerHandler.UsecasesForDeleteMember
	registerHandler.UsecasesForLeaveChat
	registerHandler.UsecasesForMyChats
	registerHandler.UsecasesForMyInvitations
	registerHandler.UsecasesForOauthAuthorize
	registerHandler.UsecasesForOauthCallback
	registerHandler.UsecasesForSendInvitation
	registerHandler.UsecasesForUpdateName
}
