// Code generated by mockery v2.52.4. DO NOT EDIT.

package usecases

import mock "github.com/stretchr/testify/mock"

// HistoryMock is an autogenerated mock type for the History type
type HistoryMock struct {
	mock.Mock
}

type HistoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HistoryMock) EXPECT() *HistoryMock_Expecter {
	return &HistoryMock_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: obj
func (_m *HistoryMock) Write(obj any) error {
	ret := _m.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HistoryMock_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type HistoryMock_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - obj any
func (_e *HistoryMock_Expecter) Write(obj interface{}) *HistoryMock_Write_Call {
	return &HistoryMock_Write_Call{Call: _e.mock.On("Write", obj)}
}

func (_c *HistoryMock_Write_Call) Run(run func(obj any)) *HistoryMock_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *HistoryMock_Write_Call) Return(_a0 error) *HistoryMock_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HistoryMock_Write_Call) RunAndReturn(run func(any) error) *HistoryMock_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewHistoryMock creates a new instance of HistoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryMock {
	mock := &HistoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
