// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForEvents creates a new instance of UsecasesForEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForEvents {
	mock := &UsecasesForEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForEvents is an autogenerated mock type for the UsecasesForEvents type
type UsecasesForEvents struct {
	mock.Mock
}

type UsecasesForEvents_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForEvents) EXPECT() *UsecasesForEvents_Expecter {
	return &UsecasesForEvents_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForEvents
func (_mock *UsecasesForEvents) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForEvents_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForEvents_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForEvents_Expecter) FindSessions(in interface{}) *UsecasesForEvents_FindSessions_Call {
	return &UsecasesForEvents_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForEvents_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForEvents_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForEvents_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForEvents_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForEvents_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForEvents_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}
