// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/chat_invitations"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForChatInvitations creates a new instance of UsecasesForChatInvitations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForChatInvitations(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForChatInvitations {
	mock := &UsecasesForChatInvitations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForChatInvitations is an autogenerated mock type for the UsecasesForChatInvitations type
type UsecasesForChatInvitations struct {
	mock.Mock
}

type UsecasesForChatInvitations_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForChatInvitations) EXPECT() *UsecasesForChatInvitations_Expecter {
	return &UsecasesForChatInvitations_Expecter{mock: &_m.Mock}
}

// ChatInvitations provides a mock function for the type UsecasesForChatInvitations
func (_mock *UsecasesForChatInvitations) ChatInvitations(in chatInvitations.In) (chatInvitations.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ChatInvitations")
	}

	var r0 chatInvitations.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(chatInvitations.In) (chatInvitations.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(chatInvitations.In) chatInvitations.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(chatInvitations.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(chatInvitations.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForChatInvitations_ChatInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatInvitations'
type UsecasesForChatInvitations_ChatInvitations_Call struct {
	*mock.Call
}

// ChatInvitations is a helper method to define mock.On call
//   - in chatInvitations.In
func (_e *UsecasesForChatInvitations_Expecter) ChatInvitations(in interface{}) *UsecasesForChatInvitations_ChatInvitations_Call {
	return &UsecasesForChatInvitations_ChatInvitations_Call{Call: _e.mock.On("ChatInvitations", in)}
}

func (_c *UsecasesForChatInvitations_ChatInvitations_Call) Run(run func(in chatInvitations.In)) *UsecasesForChatInvitations_ChatInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chatInvitations.In
		if args[0] != nil {
			arg0 = args[0].(chatInvitations.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForChatInvitations_ChatInvitations_Call) Return(out chatInvitations.Out, err error) *UsecasesForChatInvitations_ChatInvitations_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForChatInvitations_ChatInvitations_Call) RunAndReturn(run func(in chatInvitations.In) (chatInvitations.Out, error)) *UsecasesForChatInvitations_ChatInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessions provides a mock function for the type UsecasesForChatInvitations
func (_mock *UsecasesForChatInvitations) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForChatInvitations_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForChatInvitations_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForChatInvitations_Expecter) FindSessions(in interface{}) *UsecasesForChatInvitations_FindSessions_Call {
	return &UsecasesForChatInvitations_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForChatInvitations_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForChatInvitations_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForChatInvitations_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForChatInvitations_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForChatInvitations_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForChatInvitations_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}
