// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/delete_member"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForDeleteMember creates a new instance of UsecasesForDeleteMember. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForDeleteMember(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForDeleteMember {
	mock := &UsecasesForDeleteMember{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForDeleteMember is an autogenerated mock type for the UsecasesForDeleteMember type
type UsecasesForDeleteMember struct {
	mock.Mock
}

type UsecasesForDeleteMember_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForDeleteMember) EXPECT() *UsecasesForDeleteMember_Expecter {
	return &UsecasesForDeleteMember_Expecter{mock: &_m.Mock}
}

// DeleteMember provides a mock function for the type UsecasesForDeleteMember
func (_mock *UsecasesForDeleteMember) DeleteMember(in deleteMember.In) (deleteMember.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMember")
	}

	var r0 deleteMember.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(deleteMember.In) (deleteMember.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(deleteMember.In) deleteMember.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(deleteMember.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(deleteMember.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForDeleteMember_DeleteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMember'
type UsecasesForDeleteMember_DeleteMember_Call struct {
	*mock.Call
}

// DeleteMember is a helper method to define mock.On call
//   - in deleteMember.In
func (_e *UsecasesForDeleteMember_Expecter) DeleteMember(in interface{}) *UsecasesForDeleteMember_DeleteMember_Call {
	return &UsecasesForDeleteMember_DeleteMember_Call{Call: _e.mock.On("DeleteMember", in)}
}

func (_c *UsecasesForDeleteMember_DeleteMember_Call) Run(run func(in deleteMember.In)) *UsecasesForDeleteMember_DeleteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 deleteMember.In
		if args[0] != nil {
			arg0 = args[0].(deleteMember.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForDeleteMember_DeleteMember_Call) Return(out deleteMember.Out, err error) *UsecasesForDeleteMember_DeleteMember_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForDeleteMember_DeleteMember_Call) RunAndReturn(run func(in deleteMember.In) (deleteMember.Out, error)) *UsecasesForDeleteMember_DeleteMember_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessions provides a mock function for the type UsecasesForDeleteMember
func (_mock *UsecasesForDeleteMember) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForDeleteMember_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForDeleteMember_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForDeleteMember_Expecter) FindSessions(in interface{}) *UsecasesForDeleteMember_FindSessions_Call {
	return &UsecasesForDeleteMember_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForDeleteMember_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForDeleteMember_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForDeleteMember_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForDeleteMember_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForDeleteMember_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForDeleteMember_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}
