// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/leave_chat"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForLeaveChat creates a new instance of UsecasesForLeaveChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForLeaveChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForLeaveChat {
	mock := &UsecasesForLeaveChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForLeaveChat is an autogenerated mock type for the UsecasesForLeaveChat type
type UsecasesForLeaveChat struct {
	mock.Mock
}

type UsecasesForLeaveChat_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForLeaveChat) EXPECT() *UsecasesForLeaveChat_Expecter {
	return &UsecasesForLeaveChat_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForLeaveChat
func (_mock *UsecasesForLeaveChat) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForLeaveChat_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForLeaveChat_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForLeaveChat_Expecter) FindSessions(in interface{}) *UsecasesForLeaveChat_FindSessions_Call {
	return &UsecasesForLeaveChat_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForLeaveChat_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForLeaveChat_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForLeaveChat_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForLeaveChat_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForLeaveChat_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForLeaveChat_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveChat provides a mock function for the type UsecasesForLeaveChat
func (_mock *UsecasesForLeaveChat) LeaveChat(in leaveChat.In) (leaveChat.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for LeaveChat")
	}

	var r0 leaveChat.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(leaveChat.In) (leaveChat.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(leaveChat.In) leaveChat.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(leaveChat.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(leaveChat.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForLeaveChat_LeaveChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveChat'
type UsecasesForLeaveChat_LeaveChat_Call struct {
	*mock.Call
}

// LeaveChat is a helper method to define mock.On call
//   - in leaveChat.In
func (_e *UsecasesForLeaveChat_Expecter) LeaveChat(in interface{}) *UsecasesForLeaveChat_LeaveChat_Call {
	return &UsecasesForLeaveChat_LeaveChat_Call{Call: _e.mock.On("LeaveChat", in)}
}

func (_c *UsecasesForLeaveChat_LeaveChat_Call) Run(run func(in leaveChat.In)) *UsecasesForLeaveChat_LeaveChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 leaveChat.In
		if args[0] != nil {
			arg0 = args[0].(leaveChat.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForLeaveChat_LeaveChat_Call) Return(out leaveChat.Out, err error) *UsecasesForLeaveChat_LeaveChat_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForLeaveChat_LeaveChat_Call) RunAndReturn(run func(in leaveChat.In) (leaveChat.Out, error)) *UsecasesForLeaveChat_LeaveChat_Call {
	_c.Call.Return(run)
	return _c
}
