// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/users/oauth/init_oauth_registration"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForOAuthInitRegistration creates a new instance of UsecasesForOAuthInitRegistration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForOAuthInitRegistration(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForOAuthInitRegistration {
	mock := &UsecasesForOAuthInitRegistration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForOAuthInitRegistration is an autogenerated mock type for the UsecasesForOAuthInitRegistration type
type UsecasesForOAuthInitRegistration struct {
	mock.Mock
}

type UsecasesForOAuthInitRegistration_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForOAuthInitRegistration) EXPECT() *UsecasesForOAuthInitRegistration_Expecter {
	return &UsecasesForOAuthInitRegistration_Expecter{mock: &_m.Mock}
}

// InitOAuthRegistration provides a mock function for the type UsecasesForOAuthInitRegistration
func (_mock *UsecasesForOAuthInitRegistration) InitOAuthRegistration(in initOAuthRegistration.In) (initOAuthRegistration.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for InitOAuthRegistration")
	}

	var r0 initOAuthRegistration.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(initOAuthRegistration.In) (initOAuthRegistration.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(initOAuthRegistration.In) initOAuthRegistration.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(initOAuthRegistration.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(initOAuthRegistration.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitOAuthRegistration'
type UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call struct {
	*mock.Call
}

// InitOAuthRegistration is a helper method to define mock.On call
//   - in initOAuthRegistration.In
func (_e *UsecasesForOAuthInitRegistration_Expecter) InitOAuthRegistration(in interface{}) *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call {
	return &UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call{Call: _e.mock.On("InitOAuthRegistration", in)}
}

func (_c *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call) Run(run func(in initOAuthRegistration.In)) *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 initOAuthRegistration.In
		if args[0] != nil {
			arg0 = args[0].(initOAuthRegistration.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call) Return(out initOAuthRegistration.Out, err error) *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call) RunAndReturn(run func(in initOAuthRegistration.In) (initOAuthRegistration.Out, error)) *UsecasesForOAuthInitRegistration_InitOAuthRegistration_Call {
	_c.Call.Return(run)
	return _c
}
