// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/received_invitations"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForMyInvitations creates a new instance of UsecasesForMyInvitations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForMyInvitations(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForMyInvitations {
	mock := &UsecasesForMyInvitations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForMyInvitations is an autogenerated mock type for the UsecasesForMyInvitations type
type UsecasesForMyInvitations struct {
	mock.Mock
}

type UsecasesForMyInvitations_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForMyInvitations) EXPECT() *UsecasesForMyInvitations_Expecter {
	return &UsecasesForMyInvitations_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForMyInvitations
func (_mock *UsecasesForMyInvitations) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForMyInvitations_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForMyInvitations_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForMyInvitations_Expecter) FindSessions(in interface{}) *UsecasesForMyInvitations_FindSessions_Call {
	return &UsecasesForMyInvitations_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForMyInvitations_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForMyInvitations_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForMyInvitations_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForMyInvitations_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForMyInvitations_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForMyInvitations_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ReceivedInvitations provides a mock function for the type UsecasesForMyInvitations
func (_mock *UsecasesForMyInvitations) ReceivedInvitations(in receivedInvitations.In) (receivedInvitations.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for ReceivedInvitations")
	}

	var r0 receivedInvitations.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(receivedInvitations.In) (receivedInvitations.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(receivedInvitations.In) receivedInvitations.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(receivedInvitations.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(receivedInvitations.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForMyInvitations_ReceivedInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceivedInvitations'
type UsecasesForMyInvitations_ReceivedInvitations_Call struct {
	*mock.Call
}

// ReceivedInvitations is a helper method to define mock.On call
//   - in receivedInvitations.In
func (_e *UsecasesForMyInvitations_Expecter) ReceivedInvitations(in interface{}) *UsecasesForMyInvitations_ReceivedInvitations_Call {
	return &UsecasesForMyInvitations_ReceivedInvitations_Call{Call: _e.mock.On("ReceivedInvitations", in)}
}

func (_c *UsecasesForMyInvitations_ReceivedInvitations_Call) Run(run func(in receivedInvitations.In)) *UsecasesForMyInvitations_ReceivedInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 receivedInvitations.In
		if args[0] != nil {
			arg0 = args[0].(receivedInvitations.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForMyInvitations_ReceivedInvitations_Call) Return(out receivedInvitations.Out, err error) *UsecasesForMyInvitations_ReceivedInvitations_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForMyInvitations_ReceivedInvitations_Call) RunAndReturn(run func(in receivedInvitations.In) (receivedInvitations.Out, error)) *UsecasesForMyInvitations_ReceivedInvitations_Call {
	_c.Call.Return(run)
	return _c
}
