// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/cancel_invitation"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForCancelInvitation creates a new instance of UsecasesForCancelInvitation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForCancelInvitation(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForCancelInvitation {
	mock := &UsecasesForCancelInvitation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForCancelInvitation is an autogenerated mock type for the UsecasesForCancelInvitation type
type UsecasesForCancelInvitation struct {
	mock.Mock
}

type UsecasesForCancelInvitation_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForCancelInvitation) EXPECT() *UsecasesForCancelInvitation_Expecter {
	return &UsecasesForCancelInvitation_Expecter{mock: &_m.Mock}
}

// CancelInvitation provides a mock function for the type UsecasesForCancelInvitation
func (_mock *UsecasesForCancelInvitation) CancelInvitation(in cancelInvitation.In) (cancelInvitation.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvitation")
	}

	var r0 cancelInvitation.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cancelInvitation.In) (cancelInvitation.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(cancelInvitation.In) cancelInvitation.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(cancelInvitation.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(cancelInvitation.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForCancelInvitation_CancelInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvitation'
type UsecasesForCancelInvitation_CancelInvitation_Call struct {
	*mock.Call
}

// CancelInvitation is a helper method to define mock.On call
//   - in cancelInvitation.In
func (_e *UsecasesForCancelInvitation_Expecter) CancelInvitation(in interface{}) *UsecasesForCancelInvitation_CancelInvitation_Call {
	return &UsecasesForCancelInvitation_CancelInvitation_Call{Call: _e.mock.On("CancelInvitation", in)}
}

func (_c *UsecasesForCancelInvitation_CancelInvitation_Call) Run(run func(in cancelInvitation.In)) *UsecasesForCancelInvitation_CancelInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cancelInvitation.In
		if args[0] != nil {
			arg0 = args[0].(cancelInvitation.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForCancelInvitation_CancelInvitation_Call) Return(out cancelInvitation.Out, err error) *UsecasesForCancelInvitation_CancelInvitation_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForCancelInvitation_CancelInvitation_Call) RunAndReturn(run func(in cancelInvitation.In) (cancelInvitation.Out, error)) *UsecasesForCancelInvitation_CancelInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessions provides a mock function for the type UsecasesForCancelInvitation
func (_mock *UsecasesForCancelInvitation) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForCancelInvitation_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForCancelInvitation_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForCancelInvitation_Expecter) FindSessions(in interface{}) *UsecasesForCancelInvitation_FindSessions_Call {
	return &UsecasesForCancelInvitation_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForCancelInvitation_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForCancelInvitation_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForCancelInvitation_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForCancelInvitation_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForCancelInvitation_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForCancelInvitation_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}
