// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/my_chats"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForMyChats creates a new instance of UsecasesForMyChats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForMyChats(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForMyChats {
	mock := &UsecasesForMyChats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForMyChats is an autogenerated mock type for the UsecasesForMyChats type
type UsecasesForMyChats struct {
	mock.Mock
}

type UsecasesForMyChats_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForMyChats) EXPECT() *UsecasesForMyChats_Expecter {
	return &UsecasesForMyChats_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForMyChats
func (_mock *UsecasesForMyChats) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForMyChats_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForMyChats_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForMyChats_Expecter) FindSessions(in interface{}) *UsecasesForMyChats_FindSessions_Call {
	return &UsecasesForMyChats_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForMyChats_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForMyChats_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForMyChats_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForMyChats_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForMyChats_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForMyChats_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// MyChats provides a mock function for the type UsecasesForMyChats
func (_mock *UsecasesForMyChats) MyChats(in myChats.In) (myChats.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for MyChats")
	}

	var r0 myChats.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(myChats.In) (myChats.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(myChats.In) myChats.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(myChats.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(myChats.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForMyChats_MyChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyChats'
type UsecasesForMyChats_MyChats_Call struct {
	*mock.Call
}

// MyChats is a helper method to define mock.On call
//   - in myChats.In
func (_e *UsecasesForMyChats_Expecter) MyChats(in interface{}) *UsecasesForMyChats_MyChats_Call {
	return &UsecasesForMyChats_MyChats_Call{Call: _e.mock.On("MyChats", in)}
}

func (_c *UsecasesForMyChats_MyChats_Call) Run(run func(in myChats.In)) *UsecasesForMyChats_MyChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 myChats.In
		if args[0] != nil {
			arg0 = args[0].(myChats.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForMyChats_MyChats_Call) Return(out myChats.Out, err error) *UsecasesForMyChats_MyChats_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForMyChats_MyChats_Call) RunAndReturn(run func(in myChats.In) (myChats.Out, error)) *UsecasesForMyChats_MyChats_Call {
	_c.Call.Return(run)
	return _c
}
