// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/users/basic_auth/basic_auth_registration"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForRegistrationByPassword creates a new instance of UsecasesForRegistrationByPassword. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForRegistrationByPassword(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForRegistrationByPassword {
	mock := &UsecasesForRegistrationByPassword{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForRegistrationByPassword is an autogenerated mock type for the UsecasesForRegistrationByPassword type
type UsecasesForRegistrationByPassword struct {
	mock.Mock
}

type UsecasesForRegistrationByPassword_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForRegistrationByPassword) EXPECT() *UsecasesForRegistrationByPassword_Expecter {
	return &UsecasesForRegistrationByPassword_Expecter{mock: &_m.Mock}
}

// BasicAuthRegistration provides a mock function for the type UsecasesForRegistrationByPassword
func (_mock *UsecasesForRegistrationByPassword) BasicAuthRegistration(in basicAuthRegistration.In) (basicAuthRegistration.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for BasicAuthRegistration")
	}

	var r0 basicAuthRegistration.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(basicAuthRegistration.In) (basicAuthRegistration.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(basicAuthRegistration.In) basicAuthRegistration.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(basicAuthRegistration.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(basicAuthRegistration.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForRegistrationByPassword_BasicAuthRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BasicAuthRegistration'
type UsecasesForRegistrationByPassword_BasicAuthRegistration_Call struct {
	*mock.Call
}

// BasicAuthRegistration is a helper method to define mock.On call
//   - in basicAuthRegistration.In
func (_e *UsecasesForRegistrationByPassword_Expecter) BasicAuthRegistration(in interface{}) *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call {
	return &UsecasesForRegistrationByPassword_BasicAuthRegistration_Call{Call: _e.mock.On("BasicAuthRegistration", in)}
}

func (_c *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call) Run(run func(in basicAuthRegistration.In)) *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 basicAuthRegistration.In
		if args[0] != nil {
			arg0 = args[0].(basicAuthRegistration.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call) Return(out basicAuthRegistration.Out, err error) *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call) RunAndReturn(run func(in basicAuthRegistration.In) (basicAuthRegistration.Out, error)) *UsecasesForRegistrationByPassword_BasicAuthRegistration_Call {
	_c.Call.Return(run)
	return _c
}
