// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/create_chat"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForCreateChat creates a new instance of UsecasesForCreateChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForCreateChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForCreateChat {
	mock := &UsecasesForCreateChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForCreateChat is an autogenerated mock type for the UsecasesForCreateChat type
type UsecasesForCreateChat struct {
	mock.Mock
}

type UsecasesForCreateChat_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForCreateChat) EXPECT() *UsecasesForCreateChat_Expecter {
	return &UsecasesForCreateChat_Expecter{mock: &_m.Mock}
}

// CreateChat provides a mock function for the type UsecasesForCreateChat
func (_mock *UsecasesForCreateChat) CreateChat(in createChat.In) (createChat.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 createChat.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(createChat.In) (createChat.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(createChat.In) createChat.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(createChat.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(createChat.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForCreateChat_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type UsecasesForCreateChat_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - in createChat.In
func (_e *UsecasesForCreateChat_Expecter) CreateChat(in interface{}) *UsecasesForCreateChat_CreateChat_Call {
	return &UsecasesForCreateChat_CreateChat_Call{Call: _e.mock.On("CreateChat", in)}
}

func (_c *UsecasesForCreateChat_CreateChat_Call) Run(run func(in createChat.In)) *UsecasesForCreateChat_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 createChat.In
		if args[0] != nil {
			arg0 = args[0].(createChat.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForCreateChat_CreateChat_Call) Return(out createChat.Out, err error) *UsecasesForCreateChat_CreateChat_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForCreateChat_CreateChat_Call) RunAndReturn(run func(in createChat.In) (createChat.Out, error)) *UsecasesForCreateChat_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessions provides a mock function for the type UsecasesForCreateChat
func (_mock *UsecasesForCreateChat) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForCreateChat_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForCreateChat_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForCreateChat_Expecter) FindSessions(in interface{}) *UsecasesForCreateChat_FindSessions_Call {
	return &UsecasesForCreateChat_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForCreateChat_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForCreateChat_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForCreateChat_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForCreateChat_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForCreateChat_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForCreateChat_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}
