// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	"github.com/nice-pea/npchat/internal/usecases/users/user_profile"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForGetUser creates a new instance of UsecasesForGetUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForGetUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForGetUser {
	mock := &UsecasesForGetUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForGetUser is an autogenerated mock type for the UsecasesForGetUser type
type UsecasesForGetUser struct {
	mock.Mock
}

type UsecasesForGetUser_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForGetUser) EXPECT() *UsecasesForGetUser_Expecter {
	return &UsecasesForGetUser_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForGetUser
func (_mock *UsecasesForGetUser) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForGetUser_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForGetUser_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForGetUser_Expecter) FindSessions(in interface{}) *UsecasesForGetUser_FindSessions_Call {
	return &UsecasesForGetUser_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForGetUser_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForGetUser_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForGetUser_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForGetUser_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForGetUser_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForGetUser_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// UserProfile provides a mock function for the type UsecasesForGetUser
func (_mock *UsecasesForGetUser) UserProfile(in userProfile.In) (userProfile.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for UserProfile")
	}

	var r0 userProfile.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(userProfile.In) (userProfile.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(userProfile.In) userProfile.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(userProfile.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(userProfile.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForGetUser_UserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserProfile'
type UsecasesForGetUser_UserProfile_Call struct {
	*mock.Call
}

// UserProfile is a helper method to define mock.On call
//   - in userProfile.In
func (_e *UsecasesForGetUser_Expecter) UserProfile(in interface{}) *UsecasesForGetUser_UserProfile_Call {
	return &UsecasesForGetUser_UserProfile_Call{Call: _e.mock.On("UserProfile", in)}
}

func (_c *UsecasesForGetUser_UserProfile_Call) Run(run func(in userProfile.In)) *UsecasesForGetUser_UserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 userProfile.In
		if args[0] != nil {
			arg0 = args[0].(userProfile.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForGetUser_UserProfile_Call) Return(out userProfile.Out, err error) *UsecasesForGetUser_UserProfile_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForGetUser_UserProfile_Call) RunAndReturn(run func(in userProfile.In) (userProfile.Out, error)) *UsecasesForGetUser_UserProfile_Call {
	_c.Call.Return(run)
	return _c
}
