// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockRegisterHandler

import (
	"github.com/nice-pea/npchat/internal/usecases/chats/send_invitation"
	"github.com/nice-pea/npchat/internal/usecases/sessions/find_session"
	mock "github.com/stretchr/testify/mock"
)

// NewUsecasesForSendInvitation creates a new instance of UsecasesForSendInvitation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecasesForSendInvitation(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsecasesForSendInvitation {
	mock := &UsecasesForSendInvitation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsecasesForSendInvitation is an autogenerated mock type for the UsecasesForSendInvitation type
type UsecasesForSendInvitation struct {
	mock.Mock
}

type UsecasesForSendInvitation_Expecter struct {
	mock *mock.Mock
}

func (_m *UsecasesForSendInvitation) EXPECT() *UsecasesForSendInvitation_Expecter {
	return &UsecasesForSendInvitation_Expecter{mock: &_m.Mock}
}

// FindSessions provides a mock function for the type UsecasesForSendInvitation
func (_mock *UsecasesForSendInvitation) FindSessions(in findSession.In) (findSession.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for FindSessions")
	}

	var r0 findSession.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(findSession.In) (findSession.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(findSession.In) findSession.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(findSession.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(findSession.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForSendInvitation_FindSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessions'
type UsecasesForSendInvitation_FindSessions_Call struct {
	*mock.Call
}

// FindSessions is a helper method to define mock.On call
//   - in findSession.In
func (_e *UsecasesForSendInvitation_Expecter) FindSessions(in interface{}) *UsecasesForSendInvitation_FindSessions_Call {
	return &UsecasesForSendInvitation_FindSessions_Call{Call: _e.mock.On("FindSessions", in)}
}

func (_c *UsecasesForSendInvitation_FindSessions_Call) Run(run func(in findSession.In)) *UsecasesForSendInvitation_FindSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 findSession.In
		if args[0] != nil {
			arg0 = args[0].(findSession.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForSendInvitation_FindSessions_Call) Return(out findSession.Out, err error) *UsecasesForSendInvitation_FindSessions_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForSendInvitation_FindSessions_Call) RunAndReturn(run func(in findSession.In) (findSession.Out, error)) *UsecasesForSendInvitation_FindSessions_Call {
	_c.Call.Return(run)
	return _c
}

// SendInvitation provides a mock function for the type UsecasesForSendInvitation
func (_mock *UsecasesForSendInvitation) SendInvitation(in sendInvitation.In) (sendInvitation.Out, error) {
	ret := _mock.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for SendInvitation")
	}

	var r0 sendInvitation.Out
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sendInvitation.In) (sendInvitation.Out, error)); ok {
		return returnFunc(in)
	}
	if returnFunc, ok := ret.Get(0).(func(sendInvitation.In) sendInvitation.Out); ok {
		r0 = returnFunc(in)
	} else {
		r0 = ret.Get(0).(sendInvitation.Out)
	}
	if returnFunc, ok := ret.Get(1).(func(sendInvitation.In) error); ok {
		r1 = returnFunc(in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsecasesForSendInvitation_SendInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendInvitation'
type UsecasesForSendInvitation_SendInvitation_Call struct {
	*mock.Call
}

// SendInvitation is a helper method to define mock.On call
//   - in sendInvitation.In
func (_e *UsecasesForSendInvitation_Expecter) SendInvitation(in interface{}) *UsecasesForSendInvitation_SendInvitation_Call {
	return &UsecasesForSendInvitation_SendInvitation_Call{Call: _e.mock.On("SendInvitation", in)}
}

func (_c *UsecasesForSendInvitation_SendInvitation_Call) Run(run func(in sendInvitation.In)) *UsecasesForSendInvitation_SendInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sendInvitation.In
		if args[0] != nil {
			arg0 = args[0].(sendInvitation.In)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UsecasesForSendInvitation_SendInvitation_Call) Return(out sendInvitation.Out, err error) *UsecasesForSendInvitation_SendInvitation_Call {
	_c.Call.Return(out, err)
	return _c
}

func (_c *UsecasesForSendInvitation_SendInvitation_Call) RunAndReturn(run func(in sendInvitation.In) (sendInvitation.Out, error)) *UsecasesForSendInvitation_SendInvitation_Call {
	_c.Call.Return(run)
	return _c
}
