# Собрать образ и отправить в docker-репозиторий
name: CI/Delivery

# Запускать workflow при создании тега или ветки
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ "CI/Build", "Bump version" ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Собрать docker-образ
        run: |
          docker build -t "${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"\
            -f Containerfile\
            --build-arg VERSION="${{ github.ref_name }}"\
            --build-arg COMMIT="${{ github.sha }}"\
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") .

      - name: Войти в DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Отправить образ в DockerHub
        run: docker push "${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"
