# Создает легковесные теги на основе существующих в репозитории
name: CI/Tag bumping

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".mockery.yaml"
      - "Containerfile"
      - "LICENSE"
      - "Makefile"
      - "README.md"
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
